---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: ubuntu1804
    box: mrlesmithjr/bionic64
    memory: 1024
    cpus: 1
    interfaces:
      - auto_config: True
        ip: 192.168.250.10
        network_name: private_network
        type: static
    provision: True
provisioner:
  name: ansible
  lint:
    name: ansible-lint
    options:
      x: ["306", "503"]
verifier:
  name: testinfra
  lint:
    name: flake8
