---
- name: Converge
  hosts: all
  vars:
    postgresql_dbs:
      - name: netbox
        state: present
    postgresql_users:
      - name: netbox
        db: netbox
        password: netbox
        state: present
  roles:
    - role: ansible-postgresql
    - role: ansible-redis
    - role: ansible-netbox
